// Code generated by cssgen. DO NOT EDIT.
//
// Source: examples/04-css-layers/input
// Files scanned: 4
// Classes generated: 40
// Generated: 2026-02-06 13:52:05
//
// This file provides type-safe constants for CSS classes.
// Each constant includes metadata about layer, inheritance, and styles.

package ui

// Package ui provides type-safe CSS constants.
// This package is split into multiple files for readability:
// - styles_components.gen.go
// - styles_theme.gen.go
//
// This file contains the AllCSSClasses registry and base/utility styles.

// AllCSSClasses is a map of all CSS classes found in the source files.
// This is used by the linter to detect invalid class references.
// Generated classes, internal classes, and utility classes are all included.
var AllCSSClasses = map[string]bool{
	"block": true,
	"btn-primary": true,
	"card": true,
	"card__content": true,
	"card__title": true,
	"container": true,
	"flex": true,
	"font-bold": true,
	"font-normal": true,
	"font-semibold": true,
	"grid": true,
	"hidden": true,
	"inline-flex": true,
	"input": true,
	"input--error": true,
	"link": true,
	"mb-0": true,
	"mb-1": true,
	"mb-2": true,
	"mb-4": true,
	"mb-8": true,
	"mt-0": true,
	"mt-1": true,
	"mt-2": true,
	"mt-4": true,
	"mt-8": true,
	"reset": true,
	"text-base": true,
	"text-blue-600": true,
	"text-center": true,
	"text-gray-500": true,
	"text-gray-900": true,
	"text-left": true,
	"text-red-600": true,
	"text-right": true,
	"theme-primary": true,
	"theme-surface": true,
	"w-auto": true,
	"w-full": true,
	"w-screen": true,
}

// @layer utilities
//
//
// **Layout:**
// - display: `block`
const Block = "block"

// @layer base
//
//
// **Layout:**
// - margin-left: `auto`
// - margin-right: `auto`
// - max-width: `72rem`
// - padding-left: `1rem`
// - padding-right: `1rem`
// - [+1 more layout properties]
const Container = "container"

// @layer utilities
//
//
// **Layout:**
// - display: `flex`
const Flex = "flex"

// @layer utilities
//
//
// **Typography:**
// - font-weight: `700`
const FontBold = "font-bold"

// @layer utilities
//
//
// **Typography:**
// - font-weight: `400`
const FontNormal = "font-normal"

// @layer utilities
//
//
// **Typography:**
// - font-weight: `600`
const FontSemibold = "font-semibold"

// @layer utilities
//
//
// **Layout:**
// - display: `grid`
const Grid = "grid"

// @layer utilities
//
//
// **Layout:**
// - display: `none`
const Hidden = "hidden"

// @layer utilities
//
//
// **Layout:**
// - display: `inline-flex`
const InlineFlex = "inline-flex"

// @layer base
//
//
// **Visual:**
// - color: `#3b82f6`
// **Typography:**
// - text-decoration: `none`
// **Effects:**
// - transition: `color 0.2s`
//
// **Interactions:**
// - `:hover`: Changes color to `#2563eb`, text-decoration to `underline`
const Link = "link"

// @layer utilities
//
//
// **Layout:**
// - margin-bottom: `0`
const Mb0 = "mb-0"

// @layer utilities
//
//
// **Layout:**
// - margin-bottom: `0.25rem`
const Mb1 = "mb-1"

// @layer utilities
//
//
// **Layout:**
// - margin-bottom: `0.5rem`
const Mb2 = "mb-2"

// @layer utilities
//
//
// **Layout:**
// - margin-bottom: `1rem`
const Mb4 = "mb-4"

// @layer utilities
//
//
// **Layout:**
// - margin-bottom: `2rem`
const Mb8 = "mb-8"

// @layer utilities
//
//
// **Layout:**
// - margin-top: `0`
const Mt0 = "mt-0"

// @layer utilities
//
//
// **Layout:**
// - margin-top: `0.25rem`
const Mt1 = "mt-1"

// @layer utilities
//
//
// **Layout:**
// - margin-top: `0.5rem`
const Mt2 = "mt-2"

// @layer utilities
//
//
// **Layout:**
// - margin-top: `1rem`
const Mt4 = "mt-4"

// @layer utilities
//
//
// **Layout:**
// - margin-top: `2rem`
const Mt8 = "mt-8"

// @layer base
//
//
// **Layout:**
// - box-sizing: `border-box`
// - margin: `0`
// - padding: `0`
const Reset = "reset"

// @layer base
//
//
// **Visual:**
// - color: `#111827`
// **Typography:**
// - font-family: `system-ui, -apple-system, sans-serif`
// - font-size: `1rem`
// - line-height: `1.5`
const TextBase = "text-base"

// @layer utilities
//
//
// **Visual:**
// - color: `#2563eb`
const TextBlue600 = "text-blue-600"

// @layer utilities
//
//
// **Typography:**
// - text-align: `center`
const TextCenter = "text-center"

// @layer utilities
//
//
// **Visual:**
// - color: `#6b7280`
const TextGray500 = "text-gray-500"

// @layer utilities
//
//
// **Visual:**
// - color: `#111827`
const TextGray900 = "text-gray-900"

// @layer utilities
//
//
// **Typography:**
// - text-align: `left`
const TextLeft = "text-left"

// @layer utilities
//
//
// **Visual:**
// - color: `#dc2626`
const TextRed600 = "text-red-600"

// @layer utilities
//
//
// **Typography:**
// - text-align: `right`
const TextRight = "text-right"

// @layer utilities
//
//
// **Layout:**
// - width: `auto`
const WAuto = "w-auto"

// @layer utilities
//
//
// **Layout:**
// - width: `100%`
const WFull = "w-full"

// @layer utilities
//
//
// **Layout:**
// - width: `100vw`
const WScreen = "w-screen"

