// Code generated by cssgen. DO NOT EDIT.
//
// Component: Theme
// Generated: 2026-02-06 13:52:05

package ui

// Theme component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background-color: `var(--color-primary)`
// - color: `white`
const ThemePrimary = "theme-primary"

// **Visual:**
// - background-color: `var(--color-gray-50)`
// - color: `var(--color-gray-900)`
const ThemeSurface = "theme-surface"

