// Code generated by cssgen. DO NOT EDIT.
//
// Component: Components
// Generated: 2026-02-06 13:52:05

package ui

// Components component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Visual:**
// - background-color: `#3b82f6`
// - border: `none`
// - border-radius: `0.375rem`
// - color: `white`
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `inline-flex`
// - padding: `0.625rem 1.25rem`
// **Typography:**
// - font-weight: `500`
// **Effects:**
// - transition: `background-color 0.2s`
//
// **Interactions:**
// - `:hover`: Changes background-color to `#2563eb`
const BtnPrimary = "btn-primary"

// @layer components
//
//
// **Visual:**
// - background-color: `white`
// - border-radius: `0.5rem`
// - box-shadow: `0 1px 3px rgba(0, 0, 0, 0.1)`
// **Layout:**
// - padding: `1.5rem`
const Card = "card"

// @layer components
//
// **Base:** .card
// **Context:** Use with .card for proper styling
// **Overrides:** 2 properties (color, line-height)
//
// **Visual:**
// - color: `#6b7280`
// **Typography:**
// - line-height: `1.625`
const CardContent = "card__content"

// @layer components
//
// **Base:** .card
// **Context:** Use with .card for proper styling
// **Overrides:** 4 properties (color, font-size, font-weight, margin-bottom)
//
// **Visual:**
// - color: `#111827`
// **Layout:**
// - margin-bottom: `0.5rem`
// **Typography:**
// - font-size: `1.25rem`
// - font-weight: `600`
const CardTitle = "card__title"

// @layer components
//
//
// **Visual:**
// - background-color: `white`
// - border: `1px solid #d1d5db`
// - border-radius: `0.375rem`
// - color: `#111827`
// **Layout:**
// - padding: `0.625rem 0.875rem`
// - width: `100%`
// **Typography:**
// - font-size: `1rem`
// - line-height: `1.5`
// **Effects:**
// - transition: `border-color 0.2s, box-shadow 0.2s`
//
// **Interactions:**
// - `:focus`: Changes border-color to `#3b82f6`, box-shadow to `0 0 0 3px rgba(59, 130, 246, 0.1)`, outline to `none`
const Input = "input"

// @layer components
//
// **Base:** .input
// **Context:** Use with .input for proper styling
// **Overrides:** 1 properties (border-color)
//
// **Visual:**
// - border-color: `#ef4444`
const InputError = "input--error"

