// Code generated by cssgen. DO NOT EDIT.
//
// Component: Advanced
// Generated: 2026-02-06 14:48:46

package ui

// Advanced component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background-color: `#ef4444`
// - border-radius: `50%`
// **Layout:**
// - content: `''`
// - display: `inline-block`
// - height: `8px`
// - padding: `0.25rem 0.75rem`
// - position: `absolute`
// - [+3 more layout properties]
const Badge = "badge"

// **Layout:**
// - padding: `1rem 2rem`
const Btn = "btn"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
//
// **Layout:**
// - padding: `1rem 2rem`
const BtnLarge = "btn--large"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
//
// **Layout:**
// - padding: `1rem 2rem`
const BtnPrimary = "btn--primary"

// **Visual:**
// - border: `none`
// - opacity: `0.5`
// **Layout:**
// - cursor: `pointer`
// - padding: `0.5rem 1rem`
const Button = "button"

// **Typography:**
// - font-size: `1.25rem`
// - font-weight: `600`
const Card = "card"

// **Base:** .card
// **Context:** Use with .card for proper styling
//
// **Typography:**
// - font-size: `1.25rem`
// - font-weight: `600`
const CardHeader = "card__header"

// **Base:** .card
// **Context:** Use with .card for proper styling
//
// **Typography:**
// - font-size: `1.25rem`
// - font-weight: `600`
const CardTitle = "card__title"

// **Visual:**
// - opacity: `1`
// **Layout:**
// - display: `block`
// **Effects:**
// - transform: `translateY(0)`
const Dropdown = "dropdown"

// **Base:** .dropdown
// **Context:** Use with .dropdown for proper styling
//
// **Visual:**
// - opacity: `1`
// **Layout:**
// - display: `block`
// **Effects:**
// - transform: `translateY(0)`
const DropdownMenu = "dropdown__menu"

// **Visual:**
// - border: `1px solid #d1d5db`
// **Layout:**
// - margin-top: `0.25rem`
// - padding: `0.5rem`
//
// **Interactions:**
// - `:focus`: Changes border-color to `#3b82f6`, box-shadow to `0 0 0 3px rgba(59, 130, 246, 0.1)`
// - `:disabled`: Changes cursor to `not-allowed`, opacity to `0.5`
// - `:invalid`: Changes border-color to `#ef4444`
const Input = "input"

// **Visual:**
// - opacity: `1`
// **Layout:**
// - display: `block`
// **Effects:**
// - transform: `translateY(0)`
const IsOpen = "is-open"

// **Visual:**
// - opacity: `1`
// **Layout:**
// - pointer-events: `auto`
const IsVisible = "is-visible"

// **Layout:**
// - cursor: `pointer`
const JsTrigger = "js-trigger"

// **Layout:**
// - margin-top: `0.25rem`
const Label = "label"

// **Visual:**
// - color: `#3b82f6`
// **Typography:**
// - text-decoration: `none`
//
// **Interactions:**
// - `:hover`: Changes color to `#2563eb`, text-decoration to `underline`
// - `:focus`: Changes outline to `2px solid #3b82f6`, outline-offset to `2px`
// - `:active`: Changes color to `#1d4ed8`
// - `:visited`: Changes color to `#7c3aed`
const Link = "link"

// **Layout:**
// - margin-bottom: `0.5rem`
const Menu = "menu"

// **Base:** .menu
// **Context:** Use with .menu for proper styling
//
// **Layout:**
// - margin-bottom: `0.5rem`
const MenuItem = "menu__item"

// **Visual:**
// - opacity: `1`
// **Layout:**
// - pointer-events: `auto`
const Modal = "modal"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
//
// **Visual:**
// - opacity: `1`
// **Layout:**
// - pointer-events: `auto`
const ModalDialog = "modal__dialog"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
//
// **Visual:**
// - opacity: `1`
// **Layout:**
// - pointer-events: `auto`
const ModalOverlay = "modal__overlay"

// **Layout:**
// - padding: `0.5rem`
const Nav = "nav"

// **Base:** .nav
// **Context:** Use with .nav for proper styling
//
// **Layout:**
// - padding: `0.5rem`
const NavItem = "nav__item"

// **Typography:**
// - font-weight: `500`
const Primary = "primary"

// **Visual:**
// - color: `#9ca3af`
// **Layout:**
// - content: `'"'`
// - left: `0`
// - padding-left: `1.5rem`
// - position: `absolute`
// **Typography:**
// - font-size: `2rem`
// - font-style: `italic`
const Quote = "quote"

// **Layout:**
// - display: `flex`
const Responsive = "responsive"

// **Typography:**
// - font-weight: `500`
const Secondary = "secondary"

// **Visual:**
// - background-color: `#f3f4f6`
const Tabs = "tabs"

// **Base:** .tabs
// **Context:** Use with .tabs for proper styling
//
//
// **Interactions:**
// - `:hover`: Changes background-color to `#f3f4f6`
const TabsTab = "tabs__tab"

// **Base:** .tabs__tab
// **Context:** Use with .tabs__tab for proper styling
// **Overrides:** 1 properties (background-color)
//
// **Visual:**
// - background-color: `#f3f4f6`
const TabsTabActive = "tabs__tab--active"

// **Typography:**
// - font-weight: `500`
const Tertiary = "tertiary"

