// Code generated by cssgen. DO NOT EDIT.
//
// Source: examples/06-complex-selectors/input
// Files scanned: 1
// Classes generated: 31
// Generated: 2026-02-06 13:52:05
//
// This file provides type-safe constants for CSS classes.
// Each constant includes metadata about layer, inheritance, and styles.

package ui

// Package ui provides type-safe CSS constants.
// This package is split into multiple files for readability:
// - styles_advanced.gen.go
//
// This file contains the AllCSSClasses registry and base/utility styles.

// AllCSSClasses is a map of all CSS classes found in the source files.
// This is used by the linter to detect invalid class references.
// Generated classes, internal classes, and utility classes are all included.
var AllCSSClasses = map[string]bool{
	"_internal": true,
	"badge": true,
	"btn": true,
	"btn--large": true,
	"btn--primary": true,
	"button": true,
	"card": true,
	"card__header": true,
	"card__title": true,
	"dropdown": true,
	"dropdown__menu": true,
	"input": true,
	"is-open": true,
	"is-visible": true,
	"js-trigger": true,
	"label": true,
	"link": true,
	"menu": true,
	"menu__item": true,
	"modal": true,
	"modal__dialog": true,
	"modal__overlay": true,
	"nav": true,
	"nav__item": true,
	"primary": true,
	"quote": true,
	"responsive": true,
	"secondary": true,
	"tabs": true,
	"tabs__tab": true,
	"tabs__tab--active": true,
	"tertiary": true,
}

