version: '3'

vars:
  BINARY_NAME: cssgen
  MAIN_PATH: ./cmd/cssgen

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build cssgen binary
    cmds:
      - go build -o bin/{{.BINARY_NAME}} {{.MAIN_PATH}}

  build:all:
    desc: Build for all platforms
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o bin/{{.BINARY_NAME}}-linux-amd64 {{.MAIN_PATH}}
      - GOOS=linux GOARCH=arm64 go build -o bin/{{.BINARY_NAME}}-linux-arm64 {{.MAIN_PATH}}
      - GOOS=darwin GOARCH=amd64 go build -o bin/{{.BINARY_NAME}}-darwin-amd64 {{.MAIN_PATH}}
      - GOOS=darwin GOARCH=arm64 go build -o bin/{{.BINARY_NAME}}-darwin-arm64 {{.MAIN_PATH}}
      - GOOS=windows GOARCH=amd64 go build -o bin/{{.BINARY_NAME}}-windows-amd64.exe {{.MAIN_PATH}}

  test:
    desc: Run tests
    cmds:
      - go test -v -race ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - go tool cover -html=coverage.txt -o coverage.html
      - echo "Coverage report generated: coverage.html"

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  lint:fix:
    desc: Run linter with auto-fix
    cmds:
      - golangci-lint run --fix

  check:
    desc: Run all checks (test + lint)
    cmds:
      - task: test
      - task: lint

  install:
    desc: Install cssgen to $GOPATH/bin
    cmds:
      - go install {{.MAIN_PATH}}

  clean:
    desc: Clean build artifacts and coverage reports
    cmds:
      - rm -rf bin/
      - rm -f coverage.txt coverage.html

  fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...

  mod:tidy:
    desc: Tidy go.mod and go.sum
    cmds:
      - go mod tidy

  mod:verify:
    desc: Verify module dependencies
    cmds:
      - go mod verify

  example:
    desc: Run cssgen on testdata
    cmds:
      - go run {{.MAIN_PATH}} -source ./testdata -output-dir /tmp/cssgen-example -package example -verbose
      - echo "Output written to /tmp/cssgen-example"
