// Code generated by cssgen. DO NOT EDIT.
//
// Component: Layout
// Generated: 2026-02-06 13:52:05

package ui

// Layout component styles
//
// For the full CSS class registry, see styles.gen.go

// **Layout:**
// - position: `absolute`
const Absolute = "absolute"

// **Layout:**
// - display: `block`
const Block = "block"

// **Layout:**
// - bottom: `0`
const Bottom0 = "bottom-0"

// **Layout:**
// - position: `fixed`
const Fixed = "fixed"

// **Layout:**
// - display: `flex`
const Flex = "flex"

// **Layout:**
// - flex: `1 1 0%`
const Flex1 = "flex-1"

// **Layout:**
// - flex: `1 1 auto`
const FlexAuto = "flex-auto"

// **Layout:**
// - flex-direction: `column`
const FlexCol = "flex-col"

// **Layout:**
// - flex-direction: `column-reverse`
const FlexColReverse = "flex-col-reverse"

// **Layout:**
// - flex: `none`
const FlexNone = "flex-none"

// **Layout:**
// - flex-wrap: `nowrap`
const FlexNowrap = "flex-nowrap"

// **Layout:**
// - flex-direction: `row`
const FlexRow = "flex-row"

// **Layout:**
// - flex-direction: `row-reverse`
const FlexRowReverse = "flex-row-reverse"

// **Layout:**
// - flex-wrap: `wrap`
const FlexWrap = "flex-wrap"

// **Layout:**
// - display: `grid`
const Grid = "grid"

// **Layout:**
// - grid-template-columns: `repeat(1, minmax(0, 1fr))`
const GridCols1 = "grid-cols-1"

// **Layout:**
// - grid-template-columns: `repeat(2, minmax(0, 1fr))`
const GridCols2 = "grid-cols-2"

// **Layout:**
// - grid-template-columns: `repeat(3, minmax(0, 1fr))`
const GridCols3 = "grid-cols-3"

// **Layout:**
// - grid-template-columns: `repeat(4, minmax(0, 1fr))`
const GridCols4 = "grid-cols-4"

// **Layout:**
// - height: `auto`
const HAuto = "h-auto"

// **Layout:**
// - height: `100%`
const HFull = "h-full"

// **Layout:**
// - height: `100vh`
const HScreen = "h-screen"

// **Layout:**
// - display: `none`
const Hidden = "hidden"

// **Layout:**
// - display: `inline`
const Inline = "inline"

// **Layout:**
// - display: `inline-block`
const InlineBlock = "inline-block"

// **Layout:**
// - display: `inline-flex`
const InlineFlex = "inline-flex"

// **Layout:**
// - display: `inline-grid`
const InlineGrid = "inline-grid"

// **Layout:**
// - bottom: `0`
// - left: `0`
// - right: `0`
// - top: `0`
const Inset0 = "inset-0"

// **Layout:**
// - align-items: `baseline`
const ItemsBaseline = "items-baseline"

// **Layout:**
// - align-items: `center`
const ItemsCenter = "items-center"

// **Layout:**
// - align-items: `flex-end`
const ItemsEnd = "items-end"

// **Layout:**
// - align-items: `flex-start`
const ItemsStart = "items-start"

// **Layout:**
// - align-items: `stretch`
const ItemsStretch = "items-stretch"

// **Layout:**
// - justify-content: `space-around`
const JustifyAround = "justify-around"

// **Layout:**
// - justify-content: `space-between`
const JustifyBetween = "justify-between"

// **Layout:**
// - justify-content: `center`
const JustifyCenter = "justify-center"

// **Layout:**
// - justify-content: `flex-end`
const JustifyEnd = "justify-end"

// **Layout:**
// - justify-content: `flex-start`
const JustifyStart = "justify-start"

// **Layout:**
// - left: `0`
const Left0 = "left-0"

// **Layout:**
// - max-width: `100%`
const MaxWFull = "max-w-full"

// **Layout:**
// - max-width: `100vw`
const MaxWScreen = "max-w-screen"

// **Layout:**
// - min-width: `0`
const MinW0 = "min-w-0"

// **Layout:**
// - overflow: `auto`
const OverflowAuto = "overflow-auto"

// **Layout:**
// - overflow: `hidden`
const OverflowHidden = "overflow-hidden"

// **Layout:**
// - overflow: `scroll`
const OverflowScroll = "overflow-scroll"

// **Layout:**
// - overflow: `visible`
const OverflowVisible = "overflow-visible"

// **Layout:**
// - position: `relative`
const Relative = "relative"

// **Layout:**
// - right: `0`
const Right0 = "right-0"

// **Layout:**
// - position: `static`
const Static = "static"

// **Layout:**
// - position: `sticky`
const Sticky = "sticky"

// **Layout:**
// - top: `0`
const Top0 = "top-0"

// **Layout:**
// - width: `50%`
const W12 = "w-1-2"

// **Layout:**
// - width: `33.333333%`
const W13 = "w-1-3"

// **Layout:**
// - width: `66.666667%`
const W23 = "w-2-3"

// **Layout:**
// - width: `auto`
const WAuto = "w-auto"

// **Layout:**
// - width: `100%`
const WFull = "w-full"

// **Layout:**
// - width: `100vw`
const WScreen = "w-screen"

// **Layout:**
// - z-index: `0`
const Z0 = "z-0"

// **Layout:**
// - z-index: `10`
const Z10 = "z-10"

// **Layout:**
// - z-index: `20`
const Z20 = "z-20"

// **Layout:**
// - z-index: `50`
const Z50 = "z-50"

