// Code generated by cssgen. DO NOT EDIT.
//
// Component: Spacing
// Generated: 2026-02-06 14:48:46

package ui

// Spacing component styles
//
// For the full CSS class registry, see styles.gen.go

// **Layout:**
// - gap: `0`
const Gap0 = "gap-0"

// **Layout:**
// - gap: `0.25rem`
const Gap1 = "gap-1"

// **Layout:**
// - gap: `0.5rem`
const Gap2 = "gap-2"

// **Layout:**
// - gap: `1rem`
const Gap4 = "gap-4"

// **Layout:**
// - gap: `1.5rem`
const Gap6 = "gap-6"

// **Layout:**
// - gap: `2rem`
const Gap8 = "gap-8"

// **Layout:**
// - margin: `0`
const M0 = "m-0"

// **Layout:**
// - margin: `0.25rem`
const M1 = "m-1"

// **Layout:**
// - margin: `0.5rem`
const M2 = "m-2"

// **Layout:**
// - margin: `0.75rem`
const M3 = "m-3"

// **Layout:**
// - margin: `1rem`
const M4 = "m-4"

// **Layout:**
// - margin: `1.5rem`
const M6 = "m-6"

// **Layout:**
// - margin: `2rem`
const M8 = "m-8"

// **Layout:**
// - margin: `auto`
const MAuto = "m-auto"

// **Layout:**
// - margin-bottom: `0`
const Mb0 = "mb-0"

// **Layout:**
// - margin-bottom: `0.25rem`
const Mb1 = "mb-1"

// **Layout:**
// - margin-bottom: `4rem`
const Mb16 = "mb-16"

// **Layout:**
// - margin-bottom: `0.5rem`
const Mb2 = "mb-2"

// **Layout:**
// - margin-bottom: `1rem`
const Mb4 = "mb-4"

// **Layout:**
// - margin-bottom: `2rem`
const Mb8 = "mb-8"

// **Layout:**
// - margin-top: `0`
const Mt0 = "mt-0"

// **Layout:**
// - margin-top: `0.25rem`
const Mt1 = "mt-1"

// **Layout:**
// - margin-top: `4rem`
const Mt16 = "mt-16"

// **Layout:**
// - margin-top: `0.5rem`
const Mt2 = "mt-2"

// **Layout:**
// - margin-top: `1rem`
const Mt4 = "mt-4"

// **Layout:**
// - margin-top: `2rem`
const Mt8 = "mt-8"

// **Layout:**
// - margin-left: `0`
// - margin-right: `0`
const Mx0 = "mx-0"

// **Layout:**
// - margin-left: `1rem`
// - margin-right: `1rem`
const Mx4 = "mx-4"

// **Layout:**
// - margin-left: `auto`
// - margin-right: `auto`
const MxAuto = "mx-auto"

// **Layout:**
// - padding: `0`
const P0 = "p-0"

// **Layout:**
// - padding: `0.25rem`
const P1 = "p-1"

// **Layout:**
// - padding: `0.5rem`
const P2 = "p-2"

// **Layout:**
// - padding: `0.75rem`
const P3 = "p-3"

// **Layout:**
// - padding: `1rem`
const P4 = "p-4"

// **Layout:**
// - padding: `1.5rem`
const P6 = "p-6"

// **Layout:**
// - padding: `2rem`
const P8 = "p-8"

// **Layout:**
// - padding-left: `0.5rem`
// - padding-right: `0.5rem`
const Px2 = "px-2"

// **Layout:**
// - padding-left: `1rem`
// - padding-right: `1rem`
const Px4 = "px-4"

// **Layout:**
// - padding-left: `1.5rem`
// - padding-right: `1.5rem`
const Px6 = "px-6"

// **Layout:**
// - padding-bottom: `0.5rem`
// - padding-top: `0.5rem`
const Py2 = "py-2"

// **Layout:**
// - padding-bottom: `1rem`
// - padding-top: `1rem`
const Py4 = "py-4"

// **Layout:**
// - padding-bottom: `1.5rem`
// - padding-top: `1.5rem`
const Py6 = "py-6"

