// Code generated by cssgen. DO NOT EDIT.
//
// Component: Colors
// Generated: 2026-02-06 13:52:05

package ui

// Colors component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background-color: `#000000`
const BgBlack = "bg-black"

// **Visual:**
// - background-color: `#3b82f6`
const BgBlue500 = "bg-blue-500"

// **Visual:**
// - background-color: `#2563eb`
const BgBlue600 = "bg-blue-600"

// **Visual:**
// - background-color: `#f3f4f6`
const BgGray100 = "bg-gray-100"

// **Visual:**
// - background-color: `#e5e7eb`
const BgGray200 = "bg-gray-200"

// **Visual:**
// - background-color: `#f9fafb`
const BgGray50 = "bg-gray-50"

// **Visual:**
// - background-color: `#6b7280`
const BgGray500 = "bg-gray-500"

// **Visual:**
// - background-color: `#111827`
const BgGray900 = "bg-gray-900"

// **Visual:**
// - background-color: `#10b981`
const BgGreen500 = "bg-green-500"

// **Visual:**
// - background-color: `#059669`
const BgGreen600 = "bg-green-600"

// **Visual:**
// - background-color: `#ef4444`
const BgRed500 = "bg-red-500"

// **Visual:**
// - background-color: `#dc2626`
const BgRed600 = "bg-red-600"

// **Visual:**
// - background-color: `transparent`
const BgTransparent = "bg-transparent"

// **Visual:**
// - background-color: `#ffffff`
const BgWhite = "bg-white"

// **Visual:**
// - background-color: `#fef3c7`
const BgYellow100 = "bg-yellow-100"

// **Visual:**
// - background-color: `#f59e0b`
const BgYellow500 = "bg-yellow-500"

// **Visual:**
// - border-width: `1px`
const Border = "border"

// **Visual:**
// - border-width: `0`
const Border0 = "border-0"

// **Visual:**
// - border-width: `2px`
const Border2 = "border-2"

// **Visual:**
// - border-width: `4px`
const Border4 = "border-4"

// **Visual:**
// - border-color: `#3b82f6`
const BorderBlue500 = "border-blue-500"

// **Visual:**
// - border-style: `dashed`
const BorderDashed = "border-dashed"

// **Visual:**
// - border-color: `#e5e7eb`
const BorderGray200 = "border-gray-200"

// **Visual:**
// - border-color: `#d1d5db`
const BorderGray300 = "border-gray-300"

// **Visual:**
// - border-color: `#6b7280`
const BorderGray500 = "border-gray-500"

// **Visual:**
// - border-style: `none`
const BorderNone = "border-none"

// **Visual:**
// - border-color: `#ef4444`
const BorderRed500 = "border-red-500"

// **Visual:**
// - border-style: `solid`
const BorderSolid = "border-solid"

// **Visual:**
// - border-color: `#ffffff`
const BorderWhite = "border-white"

// **Visual:**
// - color: `#000000`
const TextBlack = "text-black"

// **Visual:**
// - color: `#3b82f6`
const TextBlue500 = "text-blue-500"

// **Visual:**
// - color: `#2563eb`
const TextBlue600 = "text-blue-600"

// **Visual:**
// - color: `#f3f4f6`
const TextGray100 = "text-gray-100"

// **Visual:**
// - color: `#d1d5db`
const TextGray300 = "text-gray-300"

// **Visual:**
// - color: `#f9fafb`
const TextGray50 = "text-gray-50"

// **Visual:**
// - color: `#6b7280`
const TextGray500 = "text-gray-500"

// **Visual:**
// - color: `#374151`
const TextGray700 = "text-gray-700"

// **Visual:**
// - color: `#111827`
const TextGray900 = "text-gray-900"

// **Visual:**
// - color: `#10b981`
const TextGreen500 = "text-green-500"

// **Visual:**
// - color: `#059669`
const TextGreen600 = "text-green-600"

// **Visual:**
// - color: `#ef4444`
const TextRed500 = "text-red-500"

// **Visual:**
// - color: `#dc2626`
const TextRed600 = "text-red-600"

// **Visual:**
// - color: `#ffffff`
const TextWhite = "text-white"

// **Visual:**
// - color: `#f59e0b`
const TextYellow500 = "text-yellow-500"

// **Visual:**
// - color: `#d97706`
const TextYellow600 = "text-yellow-600"

