// Code generated by cssgen. DO NOT EDIT.
//
// Component: Typography
// Generated: 2026-02-06 13:52:05

package ui

// Typography component styles
//
// For the full CSS class registry, see styles.gen.go

// **Typography:**
// - text-transform: `capitalize`
const Capitalize = "capitalize"

// **Typography:**
// - font-weight: `900`
const FontBlack = "font-black"

// **Typography:**
// - font-weight: `700`
const FontBold = "font-bold"

// **Typography:**
// - font-weight: `300`
const FontLight = "font-light"

// **Typography:**
// - font-weight: `500`
const FontMedium = "font-medium"

// **Typography:**
// - font-weight: `400`
const FontNormal = "font-normal"

// **Typography:**
// - font-weight: `600`
const FontSemibold = "font-semibold"

// **Typography:**
// - font-weight: `100`
const FontThin = "font-thin"

// **Typography:**
// - line-height: `2`
const LeadingLoose = "leading-loose"

// **Typography:**
// - line-height: `1`
const LeadingNone = "leading-none"

// **Typography:**
// - line-height: `1.5`
const LeadingNormal = "leading-normal"

// **Typography:**
// - line-height: `1.625`
const LeadingRelaxed = "leading-relaxed"

// **Typography:**
// - line-height: `1.25`
const LeadingTight = "leading-tight"

// **Typography:**
// - text-decoration: `line-through`
const LineThrough = "line-through"

// **Typography:**
// - text-transform: `lowercase`
const Lowercase = "lowercase"

// **Typography:**
// - text-decoration: `none`
const NoUnderline = "no-underline"

// **Typography:**
// - text-transform: `none`
const NormalCase = "normal-case"

// **Typography:**
// - font-size: `1.5rem`
// - line-height: `2rem`
const Text2xl = "text-2xl"

// **Typography:**
// - font-size: `1.875rem`
// - line-height: `2.25rem`
const Text3xl = "text-3xl"

// **Typography:**
// - font-size: `2.25rem`
// - line-height: `2.5rem`
const Text4xl = "text-4xl"

// **Typography:**
// - font-size: `1rem`
// - line-height: `1.5rem`
const TextBase = "text-base"

// **Typography:**
// - text-align: `center`
const TextCenter = "text-center"

// **Typography:**
// - text-align: `justify`
const TextJustify = "text-justify"

// **Typography:**
// - text-align: `left`
const TextLeft = "text-left"

// **Typography:**
// - font-size: `1.125rem`
// - line-height: `1.75rem`
const TextLg = "text-lg"

// **Typography:**
// - text-align: `right`
const TextRight = "text-right"

// **Typography:**
// - font-size: `0.875rem`
// - line-height: `1.25rem`
const TextSm = "text-sm"

// **Typography:**
// - font-size: `1.25rem`
// - line-height: `1.75rem`
const TextXl = "text-xl"

// **Typography:**
// - font-size: `0.75rem`
// - line-height: `1rem`
const TextXs = "text-xs"

// **Typography:**
// - letter-spacing: `0`
const TrackingNormal = "tracking-normal"

// **Typography:**
// - letter-spacing: `-0.025em`
const TrackingTight = "tracking-tight"

// **Typography:**
// - letter-spacing: `0.025em`
const TrackingWide = "tracking-wide"

// **Layout:**
// - overflow: `hidden`
// **Typography:**
// - text-overflow: `ellipsis`
// - white-space: `nowrap`
const Truncate = "truncate"

// **Typography:**
// - text-decoration: `underline`
const Underline = "underline"

// **Typography:**
// - text-transform: `uppercase`
const Uppercase = "uppercase"

// **Typography:**
// - white-space: `normal`
const WhitespaceNormal = "whitespace-normal"

// **Typography:**
// - white-space: `nowrap`
const WhitespaceNowrap = "whitespace-nowrap"

// **Typography:**
// - white-space: `pre`
const WhitespacePre = "whitespace-pre"

