// Code generated by cssgen. DO NOT EDIT.
//
// Source: examples/03-component-library/input
// Files scanned: 4
// Classes generated: 50
// Generated: 2026-02-06 13:52:05
//
// This file provides type-safe constants for CSS classes.
// Each constant includes metadata about layer, inheritance, and styles.

package ui

// Package ui provides type-safe CSS constants.
// This package is split into multiple files for readability:
// - styles_alert.gen.go
// - styles_avatar.gen.go
// - styles_badge.gen.go
// - styles_modal.gen.go
//
// This file contains the AllCSSClasses registry and base/utility styles.

// AllCSSClasses is a map of all CSS classes found in the source files.
// This is used by the linter to detect invalid class references.
// Generated classes, internal classes, and utility classes are all included.
var AllCSSClasses = map[string]bool{
	"alert": true,
	"alert--error": true,
	"alert--info": true,
	"alert--outline": true,
	"alert--success": true,
	"alert--warning": true,
	"alert__actions": true,
	"alert__close": true,
	"alert__content": true,
	"alert__description": true,
	"alert__icon": true,
	"alert__title": true,
	"avatar": true,
	"avatar--lg": true,
	"avatar--md": true,
	"avatar--rounded": true,
	"avatar--sm": true,
	"avatar--square": true,
	"avatar--xl": true,
	"avatar--xs": true,
	"avatar__img": true,
	"avatar__initials": true,
	"avatar__status": true,
	"avatar__status--away": true,
	"avatar__status--busy": true,
	"avatar__status--online": true,
	"badge": true,
	"badge--error": true,
	"badge--info": true,
	"badge--lg": true,
	"badge--neutral": true,
	"badge--outline": true,
	"badge--pill": true,
	"badge--sm": true,
	"badge--success": true,
	"badge--warning": true,
	"badge__dot": true,
	"modal": true,
	"modal--closing": true,
	"modal--hidden": true,
	"modal__body": true,
	"modal__close": true,
	"modal__dialog": true,
	"modal__dialog--full": true,
	"modal__dialog--lg": true,
	"modal__dialog--sm": true,
	"modal__dialog--xl": true,
	"modal__footer": true,
	"modal__header": true,
	"modal__title": true,
}

