// Code generated by cssgen. DO NOT EDIT.
//
// Component: Avatar
// Generated: 2026-02-06 14:48:46

package ui

// Avatar component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background-color: `#e5e7eb`
// - border-radius: `9999px`
// - color: `#6b7280`
// **Layout:**
// - align-items: `center`
// - display: `inline-flex`
// - flex-shrink: `0`
// - justify-content: `center`
// - overflow: `hidden`
// - [+1 more layout properties]
// **Typography:**
// - font-weight: `500`
const Avatar = "avatar"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 3 properties (height, object-fit, width)
//
// **Layout:**
// - height: `100%`
// - object-fit: `cover`
// - width: `100%`
const AvatarImg = "avatar__img"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 2 properties (text-transform, user-select)
//
// **Layout:**
// - user-select: `none`
// **Typography:**
// - text-transform: `uppercase`
const AvatarInitials = "avatar__initials"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 3 properties (font-size, height, width)
//
// **Layout:**
// - height: `3rem`
// - width: `3rem`
// **Typography:**
// - font-size: `1rem`
const AvatarLg = "avatar--lg"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 3 properties (font-size, height, width)
//
// **Layout:**
// - height: `2.5rem`
// - width: `2.5rem`
// **Typography:**
// - font-size: `0.875rem`
const AvatarMd = "avatar--md"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 1 properties (border-radius)
//
// **Visual:**
// - border-radius: `0.5rem`
const AvatarRounded = "avatar--rounded"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 3 properties (font-size, height, width)
//
// **Layout:**
// - height: `2rem`
// - width: `2rem`
// **Typography:**
// - font-size: `0.75rem`
const AvatarSm = "avatar--sm"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 1 properties (border-radius)
//
// **Visual:**
// - border-radius: `0.375rem`
const AvatarSquare = "avatar--square"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 7 properties (background-color, border, bottom, height, position, right, width)
//
// **Visual:**
// - background-color: `#d1d5db`
// - border: `2px solid white`
// - border-radius: `9999px`
// **Layout:**
// - bottom: `0`
// - height: `25%`
// - position: `absolute`
// - right: `0`
// - width: `25%`
const AvatarStatus = "avatar__status"

// **Base:** .avatar__status
// **Context:** Use with .avatar__status for proper styling
// **Overrides:** 1 properties (background-color)
//
// **Visual:**
// - background-color: `#f59e0b`
const AvatarStatusAway = "avatar__status--away"

// **Base:** .avatar__status
// **Context:** Use with .avatar__status for proper styling
// **Overrides:** 1 properties (background-color)
//
// **Visual:**
// - background-color: `#ef4444`
const AvatarStatusBusy = "avatar__status--busy"

// **Base:** .avatar__status
// **Context:** Use with .avatar__status for proper styling
// **Overrides:** 1 properties (background-color)
//
// **Visual:**
// - background-color: `#10b981`
const AvatarStatusOnline = "avatar__status--online"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 3 properties (font-size, height, width)
//
// **Layout:**
// - height: `4rem`
// - width: `4rem`
// **Typography:**
// - font-size: `1.25rem`
const AvatarXl = "avatar--xl"

// **Base:** .avatar
// **Context:** Use with .avatar for proper styling
// **Overrides:** 3 properties (font-size, height, width)
//
// **Layout:**
// - height: `1.5rem`
// - width: `1.5rem`
// **Typography:**
// - font-size: `0.625rem`
const AvatarXs = "avatar--xs"

