// Code generated by cssgen. DO NOT EDIT.
//
// Component: Modal
// Generated: 2026-02-06 13:52:05

package ui

// Modal component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background-color: `rgba(0, 0, 0, 0.5)`
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - inset: `0`
// - justify-content: `center`
// - padding: `1rem`
// - [+2 more layout properties]
// **Effects:**
// - backdrop-filter: `blur(4px)`
const Modal = "modal"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
// **Overrides:** 3 properties (flex, overflow-y, padding)
//
// **Layout:**
// - flex: `1`
// - overflow-y: `auto`
// - padding: `1.5rem`
const ModalBody = "modal__body"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
// **Overrides:** 7 properties (background, border, border-radius, color, cursor, padding, transition)
//
// **Visual:**
// - background: `transparent`
// - border: `none`
// - border-radius: `0.375rem`
// - color: `#6b7280`
// **Layout:**
// - cursor: `pointer`
// - padding: `0.5rem`
// **Effects:**
// - transition: `all 0.2s`
//
// **Interactions:**
// - `:hover`: Changes background-color to `#f3f4f6`, color to `#111827`
const ModalClose = "modal__close"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
// **Overrides:** 1 properties (animation)
//
// **Effects:**
// - animation: `modal-exit 0.2s ease-in`
const ModalClosing = "modal--closing"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
// **Overrides:** 9 properties (animation, background-color, border-radius, box-shadow, flex-direction, max-height, max-width, position, width)
//
// **Visual:**
// - background-color: `white`
// - border-radius: `0.5rem`
// - box-shadow: `0 20px 25px -5px rgba(0, 0, 0, 0.1)`
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - max-height: `90vh`
// - max-width: `32rem`
// - position: `relative`
// - [+1 more layout properties]
// **Effects:**
// - animation: `modal-exit 0.2s ease-in`
const ModalDialog = "modal__dialog"

// **Base:** .modal__dialog
// **Context:** Use with .modal__dialog for proper styling
// **Overrides:** 2 properties (max-height, max-width)
//
// **Layout:**
// - max-height: `calc(100vh - 2rem)`
// - max-width: `calc(100vw - 2rem)`
const ModalDialogFull = "modal__dialog--full"

// **Base:** .modal__dialog
// **Context:** Use with .modal__dialog for proper styling
// **Overrides:** 1 properties (max-width)
//
// **Layout:**
// - max-width: `48rem`
const ModalDialogLg = "modal__dialog--lg"

// **Base:** .modal__dialog
// **Context:** Use with .modal__dialog for proper styling
// **Overrides:** 1 properties (max-width)
//
// **Layout:**
// - max-width: `24rem`
const ModalDialogSm = "modal__dialog--sm"

// **Base:** .modal__dialog
// **Context:** Use with .modal__dialog for proper styling
// **Overrides:** 1 properties (max-width)
//
// **Layout:**
// - max-width: `64rem`
const ModalDialogXl = "modal__dialog--xl"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
// **Overrides:** 5 properties (background-color, border-top, gap, justify-content, padding)
//
// **Visual:**
// - background-color: `#f9fafb`
// - border-top: `1px solid #e5e7eb`
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `0.75rem`
// - justify-content: `flex-end`
// - padding: `1.5rem`
const ModalFooter = "modal__footer"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
// **Overrides:** 3 properties (border-bottom, justify-content, padding)
//
// **Visual:**
// - border-bottom: `1px solid #e5e7eb`
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - justify-content: `space-between`
// - padding: `1.5rem`
const ModalHeader = "modal__header"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
// **Overrides:** 1 properties (display)
//
// **Layout:**
// - display: `none`
const ModalHidden = "modal--hidden"

// **Base:** .modal
// **Context:** Use with .modal for proper styling
// **Overrides:** 3 properties (color, font-size, font-weight)
//
// **Visual:**
// - color: `#111827`
// **Typography:**
// - font-size: `1.125rem`
// - font-weight: `600`
const ModalTitle = "modal__title"

