// Code generated by cssgen. DO NOT EDIT.
//
// Component: Alert
// Generated: 2026-02-06 14:48:46

package ui

// Alert component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - border: `1px solid transparent`
// - border-radius: `0.5rem`
// **Layout:**
// - display: `flex`
// - gap: `0.75rem`
// - padding: `1rem`
// - position: `relative`
const Alert = "alert"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 2 properties (gap, margin-top)
//
// **Layout:**
// - display: `flex`
// - gap: `0.5rem`
// - margin-top: `0.75rem`
const AlertActions = "alert__actions"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 9 properties (background, border, cursor, opacity, padding, position, right, top, transition)
//
// **Visual:**
// - background: `transparent`
// - border: `none`
// - opacity: `0.7`
// **Layout:**
// - cursor: `pointer`
// - padding: `0.25rem`
// - position: `absolute`
// - right: `0.75rem`
// - top: `0.75rem`
// **Effects:**
// - transition: `opacity 0.2s`
//
// **Interactions:**
// - `:hover`: Changes opacity to `1`
const AlertClose = "alert__close"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 2 properties (flex, min-width)
//
// **Layout:**
// - flex: `1`
// - min-width: `0`
const AlertContent = "alert__content"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 2 properties (font-size, line-height)
//
// **Typography:**
// - font-size: `0.875rem`
// - line-height: `1.25rem`
const AlertDescription = "alert__description"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 3 properties (background-color, border-color, color)
//
// **Visual:**
// - background-color: `#fee2e2`
// - border-color: `#fca5a5`
// - color: `#991b1b`
const AlertError = "alert--error"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 3 properties (flex-shrink, height, width)
//
// **Layout:**
// - flex-shrink: `0`
// - height: `1.25rem`
// - width: `1.25rem`
const AlertIcon = "alert__icon"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 3 properties (background-color, border-color, color)
//
// **Visual:**
// - background-color: `#dbeafe`
// - border-color: `#93c5fd`
// - color: `#1e40af`
const AlertInfo = "alert--info"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 2 properties (background-color, border-width)
//
// **Visual:**
// - background-color: `transparent`
// - border-width: `2px`
const AlertOutline = "alert--outline"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 3 properties (background-color, border-color, color)
//
// **Visual:**
// - background-color: `#d1fae5`
// - border-color: `#6ee7b7`
// - color: `#065f46`
const AlertSuccess = "alert--success"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 3 properties (font-size, font-weight, margin-bottom)
//
// **Layout:**
// - margin-bottom: `0.25rem`
// **Typography:**
// - font-size: `0.875rem`
// - font-weight: `600`
const AlertTitle = "alert__title"

// **Base:** .alert
// **Context:** Use with .alert for proper styling
// **Overrides:** 3 properties (background-color, border-color, color)
//
// **Visual:**
// - background-color: `#fef3c7`
// - border-color: `#fcd34d`
// - color: `#92400e`
const AlertWarning = "alert--warning"

