// Code generated by cssgen. DO NOT EDIT.
//
// Component: Badge
// Generated: 2026-02-06 14:48:46

package ui

// Badge component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - border-radius: `9999px`
// **Layout:**
// - align-items: `center`
// - display: `inline-flex`
// - gap: `0.25rem`
// - padding: `0.125rem 0.625rem`
// **Typography:**
// - font-size: `0.75rem`
// - font-weight: `600`
// - line-height: `1.25rem`
// - white-space: `nowrap`
const Badge = "badge"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 3 properties (background-color, height, width)
//
// **Visual:**
// - background-color: `currentColor`
// - border-radius: `9999px`
// **Layout:**
// - height: `0.5rem`
// - width: `0.5rem`
const BadgeDot = "badge__dot"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#fee2e2`
// - color: `#991b1b`
const BadgeError = "badge--error"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#dbeafe`
// - color: `#1e40af`
const BadgeInfo = "badge--info"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 2 properties (font-size, padding)
//
// **Layout:**
// - padding: `0.25rem 0.75rem`
// **Typography:**
// - font-size: `0.875rem`
const BadgeLg = "badge--lg"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#f3f4f6`
// - color: `#374151`
const BadgeNeutral = "badge--neutral"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 2 properties (background-color, border)
//
// **Visual:**
// - background-color: `transparent`
// - border: `1px solid currentColor`
const BadgeOutline = "badge--outline"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 1 properties (border-radius)
//
// **Visual:**
// - border-radius: `0.25rem`
const BadgePill = "badge--pill"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 2 properties (font-size, padding)
//
// **Layout:**
// - padding: `0.0625rem 0.5rem`
// **Typography:**
// - font-size: `0.625rem`
const BadgeSm = "badge--sm"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#d1fae5`
// - color: `#065f46`
const BadgeSuccess = "badge--success"

// **Base:** .badge
// **Context:** Use with .badge for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#fef3c7`
// - color: `#92400e`
const BadgeWarning = "badge--warning"

