package cssgen

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// WriteMarkdown generates a Markdown report (shareable in GitHub, Slack, wikis)
func WriteMarkdown(w io.Writer, result *LintResult) error {
	// Count errors and warnings
	var errors, warnings int
	for _, issue := range result.Issues {
		switch issue.Severity {
		case SeverityError:
			errors++
		case SeverityWarning:
			warnings++
		}
	}

	// Header
	fmt.Fprintf(w, "# CSS Linter Report\n\n")
	fmt.Fprintf(w, "**Generated:** %s\n\n", time.Now().Format("2006-01-02 15:04:05 MST"))

	// Executive Summary
	fmt.Fprintf(w, "## Executive Summary\n\n")
	fmt.Fprintf(w, "| Metric | Value |\n")
	fmt.Fprintf(w, "|--------|-------|\n")
	fmt.Fprintf(w, "| **Total Issues** | %d (%d errors, %d warnings) |\n", len(result.Issues), errors, warnings)
	fmt.Fprintf(w, "| **Files Scanned** | %d |\n", result.FilesScanned)
	fmt.Fprintf(w, "| **Adoption Rate** | %.1f%% |\n", result.UsagePercentage)
	fmt.Fprintf(w, "| **Constants Used** | %d / %d |\n", result.ActuallyUsed, result.TotalConstants)
	fmt.Fprintf(w, "| **Migration Opportunities** | %d |\n", result.AvailableForMigration)
	fmt.Fprintf(w, "\n")

	// Adoption Progress (visual bar)
	fmt.Fprintf(w, "### Adoption Progress\n\n")
	fmt.Fprintf(w, "```\n")
	printProgressBar(w, result.UsagePercentage)
	fmt.Fprintf(w, "```\n\n")

	// Status Badge
	statusEmoji := "🔴"
	statusText := "Needs Attention"
	if result.ErrorCount == 0 && result.UsagePercentage >= 80 {
		statusEmoji = "🟢"
		statusText = "Excellent"
	} else if result.ErrorCount == 0 && result.UsagePercentage >= 50 {
		statusEmoji = "🟡"
		statusText = "Good Progress"
	}
	fmt.Fprintf(w, "**Status:** %s %s\n\n", statusEmoji, statusText)

	// Quick Wins
	if len(result.QuickWins.SingleClass) > 0 || len(result.QuickWins.MultiClass) > 0 {
		fmt.Fprintf(w, "## 🎯 Quick Wins\n\n")

		if len(result.QuickWins.SingleClass) > 0 {
			fmt.Fprintf(w, "### High Confidence (Single Class)\n\n")
			fmt.Fprintf(w, "| Rank | Class | Occurrences | Suggestion |\n")
			fmt.Fprintf(w, "|------|-------|-------------|------------|\n")
			for i, win := range result.QuickWins.SingleClass {
				if i >= 10 {
					break
				}
				fmt.Fprintf(w, "| %d | `%s` | %d | `%s` |\n",
					i+1, win.ClassName, win.Occurrences, win.Suggestion)
			}
			fmt.Fprintf(w, "\n")
		}

		if len(result.QuickWins.MultiClass) > 0 {
			fmt.Fprintf(w, "### Migration Opportunities (Multi-Class)\n\n")
			fmt.Fprintf(w, "| Rank | Class | Occurrences | Suggestion |\n")
			fmt.Fprintf(w, "|------|-------|-------------|------------|\n")
			for i, win := range result.QuickWins.MultiClass {
				if i >= 10 {
					break
				}
				// Escape pipe characters in suggestions
				suggestion := strings.ReplaceAll(win.Suggestion, "|", "\\|")
				fmt.Fprintf(w, "| %d | `%s` | %d | `%s` |\n",
					i+1, win.ClassName, win.Occurrences, suggestion)
			}
			fmt.Fprintf(w, "\n")
		}
	}

	// Errors (if any)
	if errors > 0 {
		fmt.Fprintf(w, "## ❌ Errors\n\n")
		fmt.Fprintf(w, "These classes are used but don't exist in any CSS file:\n\n")

		// Group errors by class name
		errorsByClass := make(map[string]int)
		for _, issue := range result.Issues {
			if issue.Severity == SeverityError {
				// Extract class name from message
				className := extractClassNameFromMessage(issue.Text)
				errorsByClass[className]++
			}
		}

		fmt.Fprintf(w, "| Class | Occurrences |\n")
		fmt.Fprintf(w, "|-------|-------------|\n")
		for className, count := range errorsByClass {
			fmt.Fprintf(w, "| `%s` | %d |\n", className, count)
		}
		fmt.Fprintf(w, "\n")
	}

	// Statistics
	fmt.Fprintf(w, "## 📊 Detailed Statistics\n\n")
	fmt.Fprintf(w, "| Category | Count |\n")
	fmt.Fprintf(w, "|----------|-------|\n")
	fmt.Fprintf(w, "| Total Constants Generated | %d |\n", result.TotalConstants)
	fmt.Fprintf(w, "| Actually Used (via `ui.Constant`) | %d (%.1f%%) |\n",
		result.ActuallyUsed, result.UsagePercentage)
	fmt.Fprintf(w, "| Available for Migration | %d |\n", result.AvailableForMigration)
	fmt.Fprintf(w, "| Completely Unused | %d |\n", result.CompletelyUnused)
	fmt.Fprintf(w, "| Hardcoded Classes Found | %d |\n", result.ClassesFound)
	fmt.Fprintf(w, "| Constant References | %d |\n", result.ConstantsFound)
	fmt.Fprintf(w, "\n")

	// Recommendations
	if len(result.Suggestions) > 0 {
		fmt.Fprintf(w, "## ✅ Recommendations\n\n")
		for i, suggestion := range result.Suggestions {
			fmt.Fprintf(w, "%d. %s\n", i+1, suggestion)
		}
		fmt.Fprintf(w, "\n")
	}

	// Footer
	fmt.Fprintf(w, "---\n\n")
	fmt.Fprintf(w, "*Generated by cssgen linter v1.0*\n")

	return nil
}

// extractClassNameFromMessage parses class name from error message
// Message format: "invalid CSS class \"btn--outline\" not found in stylesheet"
func extractClassNameFromMessage(message string) string {
	// Extract text between quotes
	start := strings.Index(message, `"`)
	if start == -1 {
		return ""
	}
	end := strings.Index(message[start+1:], `"`)
	if end == -1 {
		return ""
	}
	return message[start+1 : start+1+end]
}
