// Code generated by cssgen. DO NOT EDIT.
//
// Component: Navigation
// Generated: 2026-02-06 14:48:46

package ui

// Navigation component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background-color: `#1f2937`
// **Layout:**
// - display: `flex`
// - gap: `0.5rem`
// - padding: `1rem`
const Nav = "nav"

// **Base:** .nav
// **Context:** Use with .nav for proper styling
// **Overrides:** 11 properties (background-color, border-radius, color, font-size, font-weight, min-width, padding, position, right, text-align, top)
//
// **Visual:**
// - background-color: `#ef4444`
// - border-radius: `9999px`
// - color: `white`
// **Layout:**
// - min-width: `1.25rem`
// - padding: `0.125rem 0.375rem`
// - position: `absolute`
// - right: `-0.25rem`
// - top: `-0.25rem`
// **Typography:**
// - font-size: `0.75rem`
// - font-weight: `600`
// - text-align: `center`
const NavBadge = "nav__badge"

// **Base:** .nav
// **Context:** Use with .nav for proper styling
// **Overrides:** 3 properties (font-size, gap, padding)
//
// **Layout:**
// - gap: `0.25rem`
// - padding: `0.375rem 0.75rem`
// **Typography:**
// - font-size: `0.875rem`
const NavCompact = "nav--compact"

// **Base:** .nav
// **Context:** Use with .nav for proper styling
// **Overrides:** 2 properties (list-style, position)
//
// **Layout:**
// - list-style: `none`
// - position: `relative`
const NavItem = "nav__item"

// **Base:** .nav__item
// **Context:** Use with .nav__item for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#3b82f6`
// - color: `white`
const NavItemActive = "nav__item--active"

// **Base:** .nav
// **Context:** Use with .nav for proper styling
// **Overrides:** 8 properties (background-color, border-radius, color, display, font-size, padding, text-decoration, transition)
//
// **Visual:**
// - background-color: `#3b82f6`
// - border-radius: `0.375rem`
// - color: `white`
// **Layout:**
// - display: `block`
// - padding: `0.375rem 0.75rem`
// **Typography:**
// - font-size: `0.875rem`
// - text-decoration: `none`
// **Effects:**
// - transition: `background-color 0.2s`
//
// **Interactions:**
// - `:hover`: Changes background-color to `#374151`, color to `white`
const NavLink = "nav__link"

// **Base:** .nav
// **Context:** Use with .nav for proper styling
// **Overrides:** 2 properties (flex-direction, width)
//
// **Layout:**
// - flex-direction: `column`
// - width: `16rem`
const NavVertical = "nav--vertical"

