// Code generated by cssgen. DO NOT EDIT.
//
// Component: Card
// Generated: 2026-02-06 13:52:05

package ui

// Card component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background-color: `white`
// - border-radius: `0.5rem`
// - box-shadow: `0 1px 3px rgba(0, 0, 0, 0.1)`
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - overflow: `hidden`
const Card = "card"

// **Base:** .card
// **Context:** Use with .card for proper styling
// **Overrides:** 2 properties (flex, padding)
//
// **Layout:**
// - flex: `1`
// - padding: `0.75rem`
const CardBody = "card__body"

// **Base:** .card
// **Context:** Use with .card for proper styling
// **Overrides:** 1 properties (padding)
//
// **Layout:**
// - padding: `0.75rem`
const CardCompact = "card--compact"

// **Base:** .card
// **Context:** Use with .card for proper styling
// **Overrides:** 2 properties (border, box-shadow)
//
// **Visual:**
// - border: `2px solid #3b82f6`
// - box-shadow: `0 10px 15px rgba(59, 130, 246, 0.2)`
const CardFeatured = "card--featured"

// **Base:** .card
// **Context:** Use with .card for proper styling
// **Overrides:** 3 properties (background-color, border-top, padding)
//
// **Visual:**
// - background-color: `#f9fafb`
// - border-top: `1px solid #e5e7eb`
// **Layout:**
// - padding: `0.75rem`
const CardFooter = "card__footer"

// **Base:** .card
// **Context:** Use with .card for proper styling
// **Overrides:** 4 properties (border-bottom, font-size, font-weight, padding)
//
// **Visual:**
// - border-bottom: `1px solid #e5e7eb`
// **Layout:**
// - padding: `0.75rem`
// **Typography:**
// - font-size: `1.125rem`
// - font-weight: `600`
const CardHeader = "card__header"

