// Code generated by cssgen. DO NOT EDIT.
//
// Component: Button
// Generated: 2026-02-06 14:48:46

package ui

// Button component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - border: `none`
// - border-radius: `0.375rem`
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `inline-flex`
// - gap: `0.5rem`
// - padding: `0.625rem 1.25rem`
// **Typography:**
// - font-size: `1rem`
// - font-weight: `500`
// **Effects:**
// - transition: `all 0.15s ease-in-out`
const Btn = "btn"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#ef4444`
// - color: `white`
//
// **Interactions:**
// - `:hover`: Changes background-color to `#dc2626`
const BtnDanger = "btn--danger"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 3 properties (cursor, opacity, pointer-events)
//
// **Visual:**
// - opacity: `0.5`
// **Layout:**
// - cursor: `not-allowed`
// - pointer-events: `none`
const BtnDisabled = "btn--disabled"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 3 properties (flex-shrink, height, width)
//
// **Layout:**
// - flex-shrink: `0`
// - height: `1.25rem`
// - width: `1.25rem`
const BtnIcon = "btn__icon"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 2 properties (background-color, border)
//
// **Visual:**
// - background-color: `transparent`
// - border: `1px solid currentColor`
const BtnOutline = "btn--outline"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#3b82f6`
// - color: `white`
//
// **Interactions:**
// - `:hover`: Changes background-color to `#2563eb`
const BtnPrimary = "btn--primary"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 1 properties (white-space)
//
// **Typography:**
// - white-space: `nowrap`
const BtnText = "btn__text"

