// Code generated by cssgen. DO NOT EDIT.
//
// Source: examples/02-bem-methodology/input
// Files scanned: 3
// Classes generated: 20
// Generated: 2026-02-06 13:52:05
//
// This file provides type-safe constants for CSS classes.
// Each constant includes metadata about layer, inheritance, and styles.

package ui

// Package ui provides type-safe CSS constants.
// This package is split into multiple files for readability:
// - styles_button.gen.go
// - styles_card.gen.go
// - styles_navigation.gen.go
//
// This file contains the AllCSSClasses registry and base/utility styles.

// AllCSSClasses is a map of all CSS classes found in the source files.
// This is used by the linter to detect invalid class references.
// Generated classes, internal classes, and utility classes are all included.
var AllCSSClasses = map[string]bool{
	"btn": true,
	"btn--danger": true,
	"btn--disabled": true,
	"btn--outline": true,
	"btn--primary": true,
	"btn__icon": true,
	"btn__text": true,
	"card": true,
	"card--compact": true,
	"card--featured": true,
	"card__body": true,
	"card__footer": true,
	"card__header": true,
	"nav": true,
	"nav--compact": true,
	"nav--vertical": true,
	"nav__badge": true,
	"nav__item": true,
	"nav__item--active": true,
	"nav__link": true,
}

