// Code generated by cssgen. DO NOT EDIT.
//
// Source: ./input
// Files scanned: 1
// Classes generated: 5
// Generated: 2026-02-06 14:48:46
//
// This file provides type-safe constants for CSS classes.
// Each constant includes metadata about layer, inheritance, and styles.

package ui

// Package ui provides type-safe CSS constants.
// This package is split into multiple files for readability:
// - styles_buttons.gen.go
//
// This file contains the AllCSSClasses registry and base/utility styles.

// AllCSSClasses is a map of all CSS classes found in the source files.
// This is used by the linter to detect invalid class references.
// Generated classes, internal classes, and utility classes are all included.
var AllCSSClasses = map[string]bool{
	"btn": true,
	"btn--large": true,
	"btn--primary": true,
	"btn--secondary": true,
	"btn--small": true,
}

