// Code generated by cssgen. DO NOT EDIT.
//
// Component: Buttons
// Generated: 2026-02-06 14:48:46

package ui

// Buttons component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - border: `1px solid transparent`
// - border-radius: `0.375rem`
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `inline-flex`
// - justify-content: `center`
// - padding: `0.5rem 1rem`
// **Typography:**
// - font-size: `1rem`
// - font-weight: `500`
// - line-height: `1.5`
// **Effects:**
// - transition: `all 0.2s ease-in-out`
//
// **Interactions:**
// - `:hover`: Changes box-shadow to `0 4px 6px rgba(0, 0, 0, 0.1)`, transform to `translateY(-1px)`
// - `:active`: Changes transform to `translateY(0)`
const Btn = "btn"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 2 properties (font-size, padding)
//
// **Layout:**
// - padding: `0.75rem 1.5rem`
// **Typography:**
// - font-size: `1.125rem`
const BtnLarge = "btn--large"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#3b82f6`
// - color: `white`
//
// **Interactions:**
// - `:hover`: Changes background-color to `#2563eb`
const BtnPrimary = "btn--primary"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 2 properties (background-color, color)
//
// **Visual:**
// - background-color: `#6b7280`
// - color: `white`
//
// **Interactions:**
// - `:hover`: Changes background-color to `#4b5563`
const BtnSecondary = "btn--secondary"

// **Base:** .btn
// **Context:** Use with .btn for proper styling
// **Overrides:** 2 properties (font-size, padding)
//
// **Layout:**
// - padding: `0.25rem 0.75rem`
// **Typography:**
// - font-size: `0.875rem`
const BtnSmall = "btn--small"

